#!/bin/bash

# Prints out the volume percentage

VOLUME_ON_ICON=''
VOLUME_MUTED_ICON=''

get_volume(){
        #curStatus=$(pactl get-sink-mute @DEFAULT_SINK@)
        volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))

        if [ "${curStatus}" = '0%' ]
        then
            echo "$VOLUME_MUTED_ICON  $volume"
        else
            echo "$VOLUME_ON_ICON  $volume"
        fi
}

get_volume
